# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='token',
            old_name='list',
            new_name='word_list',
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
