# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0002_auto_20180127_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_list', models.TextField()),
                ('ner_list', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='word_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wordvector',
            name='vector_list',
            field=models.TextField(),
        ),
    ]
