# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0003_auto_20180129_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedtoken',
            old_name='ner_list',
            new_name='tag_list',
        ),
    ]
