# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0004_auto_20180129_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VectorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_list', models.TextField()),
            ],
        ),
    ]
