# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0005_stringlist_vectorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.TextField()),
                ('v', models.TextField()),
                ('distance', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Token',
            new_name='VectorDistanceList',
        ),
        migrations.DeleteModel(
            name='WordVector',
        ),
        migrations.RenameField(
            model_name='vectordistancelist',
            old_name='word_list',
            new_name='pair_list',
        ),
    ]
