# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0006_auto_20180130_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vectordistance',
            old_name='u',
            new_name='w1',
        ),
        migrations.RenameField(
            model_name='vectordistance',
            old_name='v',
            new_name='w2',
        ),
        migrations.AddField(
            model_name='vectordistancelist',
            name='string_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectordistancelist',
            name='vector_list',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectorlist',
            name='string_list',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
