# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0007_auto_20180205_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vectordistancelist',
            old_name='pair_list',
            new_name='distances',
        ),
    ]
