# Generated by Django 2.0.4 on 2018-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0008_auto_20180205_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_list', models.TextField()),
                ('similarity_list', models.TextField()),
            ],
        ),
    ]
