# Generated by Django 2.0.4 on 2018-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0009_similaritylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfidenceTagList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_tag_list', models.TextField()),
            ],
        ),
    ]
